# Generated by Django 4.2.11 on 2024-08-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperless', '0006_alter_applicationconfiguration_ocr_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationconfiguration',
            name='ocr_key',
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='enable_ocr',
            field=models.BooleanField(default=False, null=True, verbose_name='Enables ocr'),
        ),
    ]
