# Generated by Django 4.2.11 on 2024-10-21 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '1105_merge_20240806_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Short description of this announcement.', max_length=32, verbose_name='Label')),
                ('text', models.TextField(help_text='The actual text to be displayed.', verbose_name='Text')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Date and time after which this announcement will be displayed.', null=True, verbose_name='Start date time')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Date and time until when this announcement is to be displayed.', null=True, verbose_name='End date time')),
                ('object_pk', models.CharField(blank=True, max_length=255, verbose_name='object ID')),
                ('status', models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], default='PENDING', help_text='Current state of the task being run', max_length=30, verbose_name='State')),
                ('access_type', models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('EDIT', 'Edit'), ('VIEW', 'View')], max_length=30, verbose_name='access type')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='modified')),
                ('is_read', models.BooleanField(default=False, verbose_name='is_read')),
                ('ctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type', to='contenttypes.contenttype', verbose_name='content type')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='received_by')),
                ('received_by_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='received_by_group')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL, verbose_name='submitted_by')),
                ('submitted_by_group', models.ManyToManyField(blank=True, null=True, related_name='submitted_by_group', to='auth.group', verbose_name='submitted_by_group')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ('label',),
            },
        ),
    ]
