# Generated by Django 4.2.11 on 2024-10-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '1106_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='submitted_by_group',
        ),
        migrations.AddField(
            model_name='announcement',
            name='submitted_by_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by_group', to='auth.group', verbose_name='submitted_by_group'),
        ),
    ]
