# Generated by Django 4.2.11 on 2024-10-23 01:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1107_remove_announcement_submitted_by_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="submitted_by_group",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="access_type",
            field=models.CharField(
                blank=True,
                choices=[("OWNER", "Owner"), ("CHANGE", "Change"), ("VIEW", "View")],
                max_length=30,
                verbose_name="access type",
            ),
        ),
    ]
