# Generated by Django 4.2.11 on 2024-10-23 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '1108_remove_announcement_submitted_by_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='received_by',
        ),
        migrations.AddField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
