# Generated by Django 4.2.11 on 2025-06-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1156_boxopeningreport_alter_warehouse_boxcase_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxopeningreport',
            name='move_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.warehousemoverequest'),
        ),
    ]
